// <auto-generated />
using System;
using GestionEmpleados.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionEmpleados.Migrations
{
    [DbContext(typeof(EmpleadosDbContext))]
    partial class EmpleadosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestionEmpleados.Models.AsignacionModel", b =>
                {
                    b.Property<int>("asignacion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("asignacion_id"));

                    b.Property<int>("departamento_id")
                        .HasColumnType("int");

                    b.Property<int>("empleado_id")
                        .HasColumnType("int");

                    b.Property<string>("estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Activa");

                    b.Property<DateTime>("fecha_asignacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("asignacion_id");

                    b.HasIndex("departamento_id");

                    b.HasIndex("empleado_id", "departamento_id", "estado")
                        .HasDatabaseName("IX_Empleado_Departamento_Estado");

                    b.ToTable("Asignaciones", (string)null);
                });

            modelBuilder.Entity("GestionEmpleados.Models.DepartamentoModel", b =>
                {
                    b.Property<int>("departamento_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("departamento_id"));

                    b.Property<string>("extension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("jefe_departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ubicacion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("departamento_id");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("Departamentos", (string)null);
                });

            modelBuilder.Entity("GestionEmpleados.Models.EmpleadoModel", b =>
                {
                    b.Property<int>("empleado_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("empleado_id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("empleado_id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("GestionEmpleados.Models.AsignacionModel", b =>
                {
                    b.HasOne("GestionEmpleados.Models.DepartamentoModel", "Departamento")
                        .WithMany("Asignaciones")
                        .HasForeignKey("departamento_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEmpleados.Models.EmpleadoModel", "Empleado")
                        .WithMany("Asignaciones")
                        .HasForeignKey("empleado_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("GestionEmpleados.Models.DepartamentoModel", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("GestionEmpleados.Models.EmpleadoModel", b =>
                {
                    b.Navigation("Asignaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
